print("=========================")
print("   BEST FRIEND MAKER     ")
print("=========================")
print(" ")
print(f"Hi. I'm the computer.")
first_name = input("What's your name? ")
color = input("Hi, Ethan! What's your favorite color? ")
print(f"No way! My favorite color is also green!")
movie = input("What's your favorite movie? ")
print(f"What!?! My favorite movie is also Avengers Endgame!")
game = input("What is your favorite game? ")
print(f"Get out of here! My favorite game is football, too!")
topping = input("What is your LEAST favorite pizza topping? ")
print(f"I dislike green peppers on my pizza! Just like you!")
favorite_class = input("What is your favorite class? ")
print(f"Wow! My favorite class is Natural Resources, as well!")
print(f"We like all the same things! We should become best friends!")